version: "3.9"
services:
  php:
    build:
      context: .
      target: symfony_php
    restart: "no"
    env_file: .env
    depends_on:
      - redis
    networks:
      - default
      - entrypoint
    volumes:
      - php_socket:/var/run/php
      - .:/srv/app:rw

  redis:
    restart: "no"
    image: redis:alpine
    ports:
      - "8279:6379"
    command: [ "redis-server", "/redis.conf" ]
    volumes:
      - ./docker/redis.conf:/redis.conf

  caddy:
    build:
      context: .
      target: symfony_caddy
    depends_on:
      - php
    env_file: .env
    restart: "no"
    volumes:
      - ./public:/srv/app/public:ro
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "8280:80"
      - "8243:443"
networks:
  default:
  entrypoint:
    external: true

volumes:
  php_socket:
  caddy_data:
  caddy_config:
