controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_token:
    path: /api/v1/token

api_refresh:
    path: /api/v1/refresh
