controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_token:
    path: /api/v2/token

api_refresh:
    path: /api/v2/refresh
